services:
  backend:
    pull_policy: build
    build:
      context: ./backend
      dockerfile: Dockerfile

  frontend:
    pull_policy: build
    build:
      context: ./frontend
      dockerfile: Dockerfile
