services:
  backend:
    pull_policy: build
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        ATTENLY_PRECACHE_DOCTR_MODELS: ${ATTENLY_PRECACHE_DOCTR_MODELS:-true}

  frontend:
    pull_policy: build
    build:
      context: ./frontend
      dockerfile: Dockerfile
